vafin/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy"
  end

  root to: 'pages#home'

  get "events/admin_list", to: "events#admin_list"

  resources :events, only:[:index, :create, :show, :edit, :new] do
    resources :joinings, only:[:new, :create]
  end

  resources :joinings, only:[:index, :show, :destroy]
  resources :admins, only:[:index, :show] do
    member do
      patch :accept
      patch :reject
    end
  end

  get 'users/new', to: 'users#new'

  post 'users', to: 'users#create'

  get 'users/:id', to: 'users#show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

vafin/app/models/event.rb
class Event < ApplicationRecord
  has_many :joinings
  has_many :users, through: :joinings ,dependent: :destroy

  validates :address, presence: true
  # validates :price, presence: true
  validates :detail, presence: true
  validates :date, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  # validates :capacity, presence:true
  # validates :photo, presence:true
end

vafin/app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
    @users = User.all
  end

  def new
    @event = Event.new
    @user = 'uchida'
  end

  def create
    @event = Event.new(event_param)
      @event.user = @user
      if @event.save
        redirect_to @event
      else
        render 'new'
      end
  end

  def match_time
    @event = Event.find(params[:start_time])
  end

  def admin_list
    @events = Event.where(user_id: @user)
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event.update(event_param)
    redirect_to event_admin_list_path
  end

  def destroy
    @event.update(event_param)
    redirect_to event_admin_list_path
  end



  private

  def set_user
    @user = User.find(current_user.id)
  end

  def set_event
    @studio = Event.find(params[:id])
  end

  def event_param
    params.require(:event).permit(:title, :address, :start_time, :end_time, :detail)
  end
end

vafin/app/helpers/events_helper.rb
module EventsHelper
end

vafin/app/views/events/create.html.erb
<h1>Events#create</h1>

vafin/app/views/events/index.html.erb
<div class="container">
  <div class="row">
    <div class="card">
      <% @events.each do |event| %>
        <div class="add-event-card">
          <div class="event">
            <h2><%= link_to event.title, event_path(event) %></h2>
            <p><%= event.detail %></p>
          </div>
        </div>
      <% end %>
    </div>

    <div class="card">
      <% @users.each do |user| %>
        <% user.events.each do |event| %>
        <div class="add-event-card">
          <div class="event">
            <h2><%= link_to event.title, event_path(event) %></h2>
            <p><%= event.detail %></p>
          </div>
        </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

vafin/app/views/events/new.html.erb
<h1>event#new</h1>

<%= form_for (@event) do |f| %>
  <p><%= f.label :title %></p>
  <p><%= f.text_field :title %></p>
  <p><%= f.label :address %></p>
  <p><%= f.text_field :address %></p>
  <p><%= f.label :date %></p>
  <p><%= f.text_field :date %></p>
  <p><%= f.label :start_time %></p>
  <p><%= f.text_field :start_time %> : <%= f.text_field :end_time %></p>
  <p><%= f.label :detail %></p>
  <p><%= f.text_field :detail %></p>
  <p><%= f.submit %></p>
<% end %>

vafin/app/views/events/show.html.erb
<h1><%= @event.title %></h1>
<p><%= @event.detail %></p>
<p>date: <%= @event.date%></p>
<p>starttime <%= @event.start_time %>:<%= @event.end_time %></p>
<p><%= @event.address %></p>